Adding names to literal types
microsoft/vscode-languageserver-node pull request #1308
Opened 2023-09-06 03:41 UTC by karthiknadig

2023-09-06 03:43 UTC, karthiknadig commented
@dbaeumer I have added names to a few types. Please let me know if I the change I have made are going in the right direction. For example, I see that the changes I made in `types/main.ts` don't get picked up by meta mode generator until types is published and the types in protocol is updated. Is that the right way to update that?

2023-09-10 00:34 UTC, dbaeumer commented
They do go into the right direction and they should be picked up in the generation. Did you run `npm run symlink` in the root of the directory?

2023-09-11 17:51 UTC, karthiknadig commented
Yes, I did. I am doing this on Windows.

When i run `npm install` for `protocol` it still pulls in the published version of the package.

2023-09-11 22:41 UTC, dbaeumer commented
> When i run npm install for protocol it still pulls in the published version of the package.

`npm install` removes all symbolic links again. So you always need to do `npm install & npm run symlink`

2023-09-11 22:47 UTC, karthiknadig commented
That worked. Thanks, I will update rest of the literal types.

2023-09-14 00:29 UTC, karthiknadig commented
I have converted all of the "literal" kinds except for the one that are like below:
```
                                        "name": "range",
					"type": {
						"kind": "or",
						"items": [
							{
								"kind": "base",
								"name": "boolean"
							},
							{
								"kind": "literal",
								"value": {
									"properties": []
								}
							}
						]
					},
```
I am assuming the intent here was the allow future extensibility of type for this field. We could leave it as is.

2023-10-10 07:56 UTC, dbaeumer commented
@karthiknadig could you please undo the change in the package.json. In general I only change version numbers when releasing stuff in our releaser pipeline. And although in the metaModel.json since I generate that when I release a new version.

This makes reviewing the PR and merging a lot easier. Thanks!

2023-10-10 09:27 UTC, dbaeumer requested changes
In general please add @proposed to all

2023-10-10 09:27 UTC, dbaeumer commented on types/src/main.ts
> +export interface MarkedStringDetail {
Detail is not a good name. MarkedStringWithLanguage ?

And although deprecated we should add @since and @proposed.

2023-10-10 09:27 UTC, dbaeumer commented on protocol/src/common/protocol.ts
> + *
We should add @since 3.18.0 own type name or something to indicate the change we did.

2023-10-10 09:27 UTC, dbaeumer commented on protocol/src/common/protocol.ts
> + *
Same for ServerInfo and all other types we introduce that have already a @since tag

2023-10-10 22:40 UTC, karthiknadig commented on protocol/src/common/protocol.ts
> +export interface TextDocumentFilterPattern {
Yep. Fixed this.

2023-10-10 22:50 UTC, karthiknadig commented
I think we might have to update the `since` type in the schema to be `string[]`. I can do that in a separate PR.

2023-10-13 06:37 UTC, merged

2024-02-04 22:29 UTC, michaelpj commented
I'm not sure that marking these as "proposed" was a good idea, see: https://github.com/microsoft/vscode-languageserver-node/issues/1416