Add SemanticTokenTypes.label
microsoft/vscode-languageserver-node pull request #1423
Opened 2024-02-08 15:56 UTC by hyangah

Visual Studio Code has 'label' in its standard token types list. https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#standard-token-types-and-modifiers

Fixes #1422

2024-02-09 09:05 UTC, dbaeumer requested changes
See comments

2024-02-09 09:05 UTC, dbaeumer commented on types/src/main.ts
> +
Can you please remove the extra new line here.

2024-02-09 09:05 UTC, dbaeumer commented on client/src/common/semanticTokens.ts
>      		SemanticTokenModifiers.declaration,
Can you please remove the extra semicolon here.

2024-05-03 15:39 UTC, hyangah commented
It needs 1 more collaborator approval(s).
Is there anything else I should do to unblock this issue? Thanks!

2024-05-15 07:24 UTC, merged